### ISSUE TITLE
acks=0 breaks AIOKafkaProducer in version 0.3.1

### ISSUE THREAD

**Issue by diegoparrilla** [aio-libs/aiokafka#244]
I have just upgraded from version 0.2.2 to 0.3.1 and I have found out the following error when sending a message without confirmation (acks=0):

```python
2017-10-23 22:29:46,232 producer.py:357 aiokafka.producer:ERROR => Unexpected error in sender routine
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiokafka/producer.py", line 350, in _sender_routine
    task.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiokafka/producer.py", line 411, in _send_produce_req
    for topic, partitions in response.topics:
AttributeError: 'NoneType' object has no attribute 'topics'
```
After reviewing the source code of the `producer.py` file, it seems that the error comes when trying to iterate on `response.topics`: 

https://github.com/aio-libs/aiokafka/blob/68d95247491451aeac20a39e27c1eed190360d9d/aiokafka/producer/producer.py#L432

But the funny thing is that my producer is configured with `acks=0`, so this piece of code should never be reached because if `acks==0` then this part of the if-then-else statement should be executed:
https://github.com/aio-libs/aiokafka/blob/68d95247491451aeac20a39e27c1eed190360d9d/aiokafka/producer/producer.py#L428-L432

Once I changed acks=0 to acks=1 the producer works again seamlessly. But I would like to use acks=0 because of the logic in my solution. 

Am I doing anything wrong or is there a bug in the code about acks=0?

**Comment by tvoinarovskyi** [comment]
Yea, should be fixed by https://github.com/aio-libs/aiokafka/commit/89566365221917b68ed29f0406587f3fa3b5a99b.
