### ISSUE TITLE
Exception traceback is multiplied by number of futures

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#246]
When there is raised `RequestTimedOutError` during commiting the `AIOKafkaConnection` is closed and because of that all futures that waits in `AIOKafkaConnection._requests` have set exception. However there is reused single exception for this. And this results in having traceback of this exception strangely multiplied. Take a look at exception traceback that I got:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/messaging_client/mqclient/topic_check.py", line 159, in commit
    await self._consumer.commit(positions)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/consumer.py", line 407, in commit
    yield from self._coordinator.commit_offsets(offsets)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 544, in commit_offsets
    node_id, request, group=ConnectionGroup.COORDINATION)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 286, in _send_req
    raise err
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 280, in _send_req
    resp = yield from self._client.send(node_id, request, group=group)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/client.py", line 408, in send
    result = yield from future
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/site-packages/messaging_client/mqclient/topic_check.py", line 159, in commit
    await self._consumer.commit(positions)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/consumer.py", line 407, in commit
    yield from self._coordinator.commit_offsets(offsets)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 544, in commit_offsets
    node_id, request, group=ConnectionGroup.COORDINATION)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 286, in _send_req
    raise err
  File "/usr/local/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 280, in _send_req
    resp = yield from self._client.send(node_id, request, group=group)
  File "/usr/local/lib/python3.5/site-packages/aiokafka/client.py", line 408, in send
    result = yield from future
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
kafka.errors.ConnectionError: ConnectionError: Connection at kafka0 closed
```
You can see that the traceback is doubled. Everything since `commit` from our messaging client to `future.result` is there twice. And with next future it is there three times and so on. If there is a lot waiting futures the traceback is getting really long and eventually it can be thousands of lines of useless logs. This actually happened to us and it nearly killed our logging stack because there were tens of thousands messages (if the message is too long it is split).

I've managed to pin down the code that causes that. Following code simulates what is happening in `AIOKafkaConnection` and `AIOKafkaClient`.
```python
import asyncio
import sys

loop = asyncio.get_event_loop()

requests = []

def conn_send():
	fut = asyncio.Future(loop = loop)
	requests.append(fut)
	return asyncio.wait_for(fut, 0.1, loop = loop)


def conn_close():
	error = Exception('Connection closed')
	for fut in requests:
		if not fut.done():
			fut.set_exception(error)	
	requests.clear()


async def client_send():
	future = conn_send()
	try:
		await future
	except asyncio.TimeoutError:
		conn_close()


async def main():
	for _ in range(3):
		asyncio.ensure_future(client_send())
	await asyncio.sleep(0.2)



if __name__ == '__main__':
	loop.run_until_complete(main())

```

When you run this code you'll get output:
```
Task exception was never retrieved
future: <Task finished coro=<client_send() done, defined at fut.py:22> exception=Exception('Connection closed',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "fut.py", line 25, in client_send
    await future
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
Exception: Connection closed
Task exception was never retrieved
future: <Task finished coro=<client_send() done, defined at fut.py:22> exception=Exception('Connection closed',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "fut.py", line 25, in client_send
    await future
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "fut.py", line 25, in client_send
    await future
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
Exception: Connection closed
```
You can see that one part is repeated. When you call `client_send` `n` times you will get `n-1` exceptions that have repeated the same block of traceback `n-1` times. I don't know why this is happening or how the traceback is computed. However, easy fix for this behavior is just set every future with new exception and not reuse one. Then traceback is not repeated and we got `n-1` exceptions but with the same traceback. I think that creating new exception for each future is not so big overhead especially if you compare it to overhead of handling thousands lines long exceptions' tracebacks.

**Comment by tvoinarovskyi** [comment]
Yea had this issue in another project, can confirm. If there a lot of Futures with the same exception, you can get out of traceback bounds even.
