### ISSUE TITLE
Subscription None in GroupCoordinator._do_group_rejoin

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#306]
Hi,
thanks for the hard work on version `0.4.0`. I'm watching updates on this repo and it is pleasure to see how new features and issues are solved. 
I'm trying to update to version `0.4.0` (using kafka `0.9.0.1`, python 3.5.2) and I've encountered strange error for only one test of our wrapper over `aiokafka`. When I'm stopping consumer and unsubscribing from a topic I get following error:
```python
messaging_client/mqclient/kafka_consumer.py:110: in stop
    await self._consumer.stop()
../../.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer/consumer.py:340: in stop
    yield from self._coordinator.close()
../../.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer/group_coordinator.py:273: in close
    yield from self._coordination_task
/usr/lib/python3.5/asyncio/futures.py:361: in __iter__
    yield self  # This tells Task to wait for completion.
/usr/lib/python3.5/asyncio/tasks.py:296: in _wakeup
    future.result()
/usr/lib/python3.5/asyncio/futures.py:274: in result
    raise self._exception
../../.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer/group_coordinator.py:221: in _on_coordination_done
    fut.result()
/usr/lib/python3.5/asyncio/futures.py:274: in result
    raise self._exception
/usr/lib/python3.5/asyncio/tasks.py:239: in _step
    result = coro.send(None)
../../.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer/group_coordinator.py:559: in _coordination_routine
    success = yield from self._do_rejoin_group(subscription)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiokafka.consumer.group_coordinator.GroupCoordinator object at 0x7f484fcab8d0>, subscription = <aiokafka.consumer.subscription_state.Subscription object at 0x7f484f112470>

    @asyncio.coroutine
    def _do_rejoin_group(self, subscription):
        rebalance = CoordinatorGroupRebalance(
            self, self.group_id, self.coordinator_id,
            subscription, self._assignors, self._session_timeout_ms,
            self._retry_backoff_ms, loop=self._loop)
        assignment = yield from rebalance.perform_group_join()
    
        if not subscription.active:
            log.debug("Subscription changed during rebalance from %s to %s. "
                      "Rejoining group.",
                      subscription.topics,
>                     self._subscription.subscription.topics)
E           AttributeError: 'NoneType' object has no attribute 'topics'

../../.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer/group_coordinator.py:758: AttributeError
```
This is only happening in one of my test and unfortunately I am not able to extract it to self containing example. But we can see that `self._subscription.subscription` is `None` and this can easily happen when somebody call `client.unsubscribe` while awaiting something in `GroupCoordinator._coordinator_routine`, right? In `GroupCoordinator._coordinator_routine` is saved only reference to `Subscription` but if it is rewritten in `SubscriptionState` by None (by method `unsubscribe`) this reference suddenly points to something that is not used anymore.
This error is happening reliably, but when I change timing (add some `asyncio.sleep` before `consumer.stop`) it disappears. Still I think this can show to some problem with timing in coordinator. Am I on the right track?

**Comment by tvoinarovskyi** [comment]
Yea, probably we will have 1 or 2 errors like that in 0.4.0. There was a wrong assumption there. Probably a test is quite easy to build, you need to start rebalance and unsubscribe from topics before it ends. Probably test_coordinator will contain something similar.

**Comment by tvoinarovskyi** [comment]
You can even try simpler:

```python
consumer.subscribe(tps)
await asyncio.sleep(0.01)
consumer.unsubscribe()
await consumer.close()

**Comment by Artimi** [comment]
Hmm this 
```python
loop = asyncio.get_event_loop()
consumer = aiokafka.AIOKafkaConsumer(
    loop = loop,
    group_id=uuid.uuid4().hex,
)

tps = [TOPIC1]
consumer.subscribe(tps)
await asyncio.sleep(0.1)
consumer.unsubscribe()
await consumer.stop()
```
gives me another error:
```
INFO:aiokafka.consumer.subscription_state:Updating subscribed topics to: frozenset({'test1da5bd709b23b4638825ef07618df0d7c'})
INFO:aiokafka.consumer.consumer:Subscribed to topic(s): {'test1da5bd709b23b4638825ef07618df0d7c'}
Traceback (most recent call last):
  File "playground/consumer_stop.py", line 88, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "playground/consumer_stop.py", line 83, in main
    consumer.unsubscribe()
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/consumer.py", line 905, in unsubscribe
    self._coordinator.maybe_leave_group()
AttributeError: 'NoneType' object has no attribute 'maybe_leave_group'

```

**Comment by tvoinarovskyi** [comment]
Well, you did not start the consumer

**Comment by Artimi** [comment]
Sorry, my bad. Now I can see two errors depending of sleep I provide to the consumer. If I let it sleep for `0.01` seconds it results in problem I reported originally. If I put there `0.001` seconds (and lower) it ends with:
```
ERROR:aiokafka.consumer.group_coordinator:Unexpected error in coordinator routine
Traceback (most recent call last):
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 221, in _on_coordination_done
    fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 543, in _coordination_routine
    yield from self._on_join_prepare(assignment)
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 305, in _on_join_prepare
    self._subscription.begin_reassignment()
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/subscription_state.py", line 214, in begin_reassignment
    self._subscription._begin_reassignment()
AttributeError: 'NoneType' object has no attribute '_begin_reassignment'
Traceback (most recent call last):
  File "playground/consumer_stop.py", line 85, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "playground/consumer_stop.py", line 81, in main
    await consumer.stop()
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/consumer.py", line 340, in stop
    yield from self._coordinator.close()
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 273, in close
    yield from self._coordination_task
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 221, in _on_coordination_done
    fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 543, in _coordination_routine
    yield from self._on_join_prepare(assignment)
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/group_coordinator.py", line 305, in _on_join_prepare
    self._subscription.begin_reassignment()
  File "/home/artimis/wood/aiokafka/aiokafka/consumer/subscription_state.py", line 214, in begin_reassignment
    self._subscription._begin_reassignment()

```

**Comment by Artimi** [comment]
Hi @tvoinarovskyi, this was solved already two months ago but release of new version still wait on other tasks https://github.com/aio-libs/aiokafka/milestone/8 . Don't you want to release already solved issues and leave the rest for version `0.4.2`? This prevents us from using `0.4.x` version and I guess others would also benefit from using version where some known bugs are fixed.

**Comment by tvoinarovskyi** [comment]
Yea, was so damn busy those days(

**Comment by Artimi** [comment]
Thanks for the release @tvoinarovskyi :+1: . The last thing missing is package on PyPI and I'll be completely happy.

**Comment by tvoinarovskyi** [comment]
Yea, there was a problem with travis migration. Will retry it)
