### ISSUE TITLE
First commit after regaining connectivity causes group coordinator to raise exception and halt the loop

### ISSUE THREAD

**Issue by cannonba11** [aio-libs/aiokafka#344]
_aiokafka==0.4, kafka-python==1.3.5, tried 3 node and 1 node kafka cluster v0.8 and v1.0.0_

I am not sure if this is a bug or its by design. 
I have a scenario where I have one consumer(manual commit, subscribe not assign, getmany, has rebalance listener callbacks)  in a consumer group. The flow is a loop of consume, process, commit
I tried testing it by killing the network connection(to all kafka nodes) and reestablishing it. To start with, the consumer is running fine and committing offsets. I let the connection be down **for more than** `session_timeout_ms` . During this time the consumer process is the same, it still has the same group id and is just looping idle.  When the connection is restored, as long as I do not commit, things keep moving and I can keep reading messages again from `getmany()`. The rebalance listener callbacks are never invoked. 
As soon as I hit `consumer.commit()`, I get the expected Offset commit errors as cluster may have rebalanced - I do catch this exception in my application. At this point the `on_partitions_revoked` callback is invoked where I do another commit which actually succeeds (again this is expected). After this, the group_coordinator throws an exception and the loop comes to a standstill. Since the group_coordinator routine is a background task I'm not able to catch it. Reading through the code, I see in `on_coordination_done`, that a call is made to stop_heatbeat soon after the `on_partitions_revoked` callback and before the `on_assigned_callback` which results in a `ConnectionError` coming from the client(down from conn.py where the exception is set on the future and the connection is closed with reason=CONNECTION_BROKEN/TIMEOUT). Should the group coordinator handle this exception gracefully? I am able to catch the commit exception but the resulting rebalance that is being managed by the background task halts the loop and after that stack trace I'm not able to consume messages anymore.  Or is this intended by design (since `session_timeout_ms` had elapsed even before the connection was restored.)
When I bump up the `session_timeout_ms`, the issue does not happen as long as I keep the outage under it.

```python
Unable to update metadata from [215] <<- connection is down until this point
[2018-03-19 00:43:19,020][connectors.example][example.py][67][86434][DEBUG] In consumer, data was fetched <<- this is right after await consumer.getmany(timeout_ms=1)
[2018-03-19 00:43:19,020][connectors.example][example.py][81][86434][DEBUG] In consumer, committing <<-first commit after network restore (If I skip this call, I can keep looping with getmany giving me messages)
OffsetCommit failed for group dev-r due to group error ([Error 25] UnknownMemberIdError: dev-r), will rejoin
OffsetCommit failed for group dev-r due to group error ([Error 25] UnknownMemberIdError: dev-r), will rejoin
[2018-03-19 00:43:19,029][connectors.example][example.py][19][86434][DEBUG] In listener revoked cb, going to commit separately
[2018-03-19 00:43:19,030][connectors.example][example.py][85][86434][DEBUG] In consumer, Could not commit but caught exception:  CommitFailedError: Commit cannot be completed since the group has already rebalanced and may have assigned the partitions to another member
[2018-03-19 00:43:19,038][connectors.example][example.py][26][86434][DEBUG] In listener revoked cb, Finished committing separately
Unexpected error in coordinator routine
Traceback (most recent call last):
  File "/aiokafka/conn.py", line 212, in _read
    resp = yield from self._reader.readexactly(4)
  File "/asyncio/streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/aiokafka/consumer/group_coordinator.py", line 221, in _on_coordination_done
    fut.result()
  File "/aiokafka/consumer/group_coordinator.py", line 550, in _coordination_routine
    yield from self._stop_heartbeat_task()
  File "/aiokafka/consumer/group_coordinator.py", line 611, in _stop_heartbeat_task
    yield from self._heartbeat_task
  File "/aiokafka/consumer/group_coordinator.py", line 628, in _heartbeat_routine
    success = yield from self._do_heartbeat()
  File "/aiokafka/consumer/group_coordinator.py", line 654, in _do_heartbeat
    resp = yield from self._send_req(request)
  File "/aiokafka/consumer/group_coordinator.py", line 261, in _send_req
    raise err
  File "/aiokafka/consumer/group_coordinator.py", line 255, in _send_req
    node_id, request, group=ConnectionGroup.COORDINATION)
  File "/aiokafka/client.py", line 417, in send
    result = yield from future
  File "/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
kafka.errors.ConnectionError: ConnectionError: Connection at kafka.domain.com:9092 broken
```
 We're stuck there and do not move after that trace.

**Comment by tvoinarovskyi** [comment]
Hey there, nice description, I will try to reproduce is asap, but am really heavy loaded atm (

**Comment by tvoinarovskyi** [comment]
Ok, so the heartbeat routine fails to handle the error correctly and the error is not propagated to the caller. Can confirm this, will try to fix ASAP...

**Comment by cannonba11** [comment]
@geoffmeyers @belgum

**Comment by tvoinarovskyi** [comment]
Should be fixed by the next release. Sorry for taking forever (

**Comment by Achillesxu** [comment]
@tvoinarovskyi 👍 when to release the next version

**Comment by fahimsakri** [comment]
Is this issue fixed?

**Comment by tvoinarovskyi** [comment]
Should be fixed. If you can reproduce, than I would gladly take another look, but lets open a new issue

**Comment by pod2metra** [comment]
I catch the same erorr kafka.errors.UnknownMemberIdError: [Error 25] UnknownMemberIdError: 
on 

**aiokafka | 0.5.2
kafka-python | 1.4.6**

**Comment by tvoinarovskyi** [comment]
@pod2metra See https://github.com/aio-libs/aiokafka/issues/575 - that is probably the issue you are facing. It should be fixed in next release, as soon as I get to it ^^
