### ISSUE TITLE
Custom Logger conflicts with aiokafka logger

### ISSUE THREAD

**Issue by myaspm** [aio-libs/aiokafka#345]
Hello,

We have some apps using aiokafka and our custom logger.

This is the custom logger:

```
extra = {'hostname': socket.gethostname(), 'ip': socket.gethostbyname(socket.gethostname()), 'user': getpass.getuser()}


def get_logger():
    logging.basicConfig(
        format='%(asctime)s # %(user)s # %(hostname)s # %(ip)s # %(message)s',
        datefmt='%m/%d/%Y %I:%M:%S')

    logger = logging.getLogger("cs_report")
    logger.setLevel(logging.ERROR)
    logger = logging.LoggerAdapter(logger, extra)
    return logger
```

But whenever we get an exception about Kafka such as 'Connection Refused', aiokafka's logger conflicts with our custom logger and throws another exception like

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'user'
```

Full sample stacktrace

```
/home/asd/venvv/bin/python /home/mustafa/Downloads/pycharm-2017.2.3/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 39653 --file /home/asd/UI/app/category_score_report/run_category_score_report.py
pydev debugger: process 18901 is connecting

Connected to pydev debugger (build 172.4343.24)
--- Logging error ---
Traceback (most recent call last):
  File "/home/asd/venvv/lib/python3.6/site-packages/aiokafka/conn.py", line 212, in _read
    resp = yield from self._reader.readexactly(4)
  File "/usr/lib/python3.6/asyncio/streams.py", line 666, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asd/venvv/lib/python3.6/site-packages/aiokafka/client.py", line 159, in bootstrap
    metadata = yield from bootstrap_conn.send(metadata_request)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
kafka.errors.ConnectionError: ConnectionError: Connection at XXX:9094 broken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
KeyError: 'user'
Call stack:
  File "/home/asd/Downloads/pycharm-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/asd/Downloads/pycharm-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/asd/Downloads/pycharm-2017.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/asd/UI/app/category_score_report/run_category_score_report.py", line 234, in <module>
    loop.run_until_complete(main_process())
  File "/home/asd/UI/app/category_score_report/run_category_score_report.py", line 220, in main_process
    await consumer.start()
  File "/home/asd/venvv/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 225, in start
    yield from self._client.bootstrap()
  File "/home/asd/venvv/lib/python3.6/site-packages/aiokafka/client.py", line 162, in bootstrap
    host, port, err)
Message: 'Unable to request metadata from "%s:%s": %s'
Arguments: ('XXX', 9094, ConnectionError('Connection at XXX:9094 broken',))

Process finished with exit code 0
```

This is not happening with any other libraries we are using or with an aiokafka log level lower than warning, so i'm posting my question here. How to solve this? Thanks in advance.

**Comment by tvoinarovskyi** [comment]
I don't see how can aiokafka affect the logging at all. We don't do any kind of configuration on logging, only call loggers. Your custom logger is trying to get an undefined variable there `user`. What is `user`?

**Comment by webknjaz** [comment]
@tvoinarovskyi you might want to set up https://github.com/apps/stale for such things :)

**Comment by tvoinarovskyi** [comment]
I'm not sure it fits the project. We have a lot of issues that need attension, thou no updates are there...

**Comment by webknjaz** [comment]
You can configure longer waiting time + ignoring labels. Also, bot posts warnings first and you get notified about the stale stuff which you forgot about. Experience is pretty straightforward. And this really helps to deal with load of abandoned issues, you still do it, but manually. It's like a garbage collector :robot:
