### ISSUE TITLE
bootstrap_servers=['kafka:9092'] not work

### ISSUE THREAD

**Issue by oucb** [aio-libs/aiokafka#359]
ENVIRONMENT:
running kafka in a container with set `--net-alias=kafka`

ERROR:
Unable connect to node with id 1: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 9092), [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "kafka_to_pg.py", line 167, in <module>
    start_consume(kafka_servers, group_id, message_topic, bill_topic)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "kafka_to_pg.py", line 135, in start_consume
    await consumer.start()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 225, in start
    yield from self._client.bootstrap()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/client.py", line 185, in bootstrap
    self._api_version = yield from self.check_version()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/client.py", line 461, in check_version
    "No connection to node with id {}".format(node_id))
kafka.errors.ConnectionError: ConnectionError: No connection to node with id 1

**Comment by tvoinarovskyi** [comment]
Great. Probably kubernetes or docker-compose, was it =)

**Comment by oucb** [comment]
@tvoinarovskyi you're right，just run it in kubernetes

**Comment by Buronn** [comment]
this still doesn't work for me
