### ISSUE TITLE
Getting ConnectionResetError

### ISSUE THREAD

**Issue by vineetgoel** [aio-libs/aiokafka#361]
I am seeing a bunch of the following errors and then the consumer just stalls:

```
[2018-04-25 10:00:52,300: ERROR]: Exception in callback AIOKafkaConnection._on_read_task_error(<Task finishe...alid state',)>)
handle: <Handle AIOKafkaConnection._on_read_task_error(<Task finishe...alid state',)>)>
Traceback (most recent call last):
  File "/home/robinhood/env/lib/python3.6/site-packages/aiokafka/conn.py", line 212, in _read
    resp = yield from self._reader.readexactly(4)
  File "/home/robinhood/python-3.6.4/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/home/robinhood/python-3.6.4/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "/home/robinhood/python-3.6.4/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robinhood/env/lib/python3.6/site-packages/aiokafka/conn.py", line 117, in _on_read_task_error
    read_task.result()
  File "/home/robinhood/env/lib/python3.6/site-packages/aiokafka/conn.py", line 252, in _read
    fut.set_exception(conn_exc)
asyncio.base_futures.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:
```

**Comment by tvoinarovskyi** [comment]
Now it should handle ConnectionReset properly

**Comment by tvoinarovskyi** [comment]
Feel free to reopen if this occurs in 0.5+
