### ISSUE TITLE
how to consume only one partition of a topic

### ISSUE THREAD

**Issue by hongweishang** [aio-libs/aiokafka#365]
import asyncio
import aiokafka
from aiokafka import AIOKafkaConsumer
from aiokafka import TopicPartition

tp = TopicPartition('my_topic', 0)
loop = asyncio.get_event_loop()
consumer = AIOKafkaConsumer(loop=loop, bootstrap_servers='localhost:9091')
consumer.assign([tp])
async def f():
        async for msg in consumer:
            print(msg)
asyncio.get_event_loop().run_until_complete(f())

when i run this python file,  traceback:
raceback (most recent call last):
  File "t.py", line 17, in <module>
    asyncio.get_event_loop().run_until_complete(f())
  File "/usr/local/python3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "t.py", line 13, in f
    async for msg in consumer:
  File "/xxx/venv/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 1018, in __anext__
    return (yield from self.getone())
  File "/xxx/venv/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 949, in getone
    msg = yield from self._fetcher.next_record(partitions)
AttributeError: 'NoneType' object has no attribute 'next_record'.

why?

**Comment by tvoinarovskyi** [comment]
You have to run `await consumer.start()`

**Comment by hongweishang** [comment]
@tvoinarovskyi thanks，but it does not work.
I add "start" sentence, and AssertionError is raised.

New file is shown as below:
`import asyncio
import aiokafka
from aiokafka import AIOKafkaConsumer
from aiokafka import TopicPartition

tp = TopicPartition('my_topic', 0)
loop = asyncio.get_event_loop()
consumer = AIOKafkaConsumer(loop=loop, bootstrap_servers=['localhost:9091', 'localhost:9092'])
consumer.assign([tp])
async def f():
       await consumer.start()
       async for msg in consumer:
       print(msg)
asyncio.get_event_loop().run_until_complete(f())`


traceback is shown as below:
Traceback (most recent call last):
  File "t.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(f())
  File "/usr/local/python3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "t.py", line 14, in f
    await consumer.start()
  File "/xxx/venv/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 270, in start
    self._coordinator.assign_all_partitions(check_unknown=True)
  File "/xxx/venv/lib/python3.6/site-packages/aiokafka/consumer/group_coordinator.py", line 103, in assign_all_partitions
    self._subscription.assign_from_subscribed(partitions)
  File "/xxx/venv/lib/python3.6/site-packages/aiokafka/consumer/subscription_state.py", line 202, in assign_from_subscribed
    SubscriptionType.AUTO_PATTERN, SubscriptionType.AUTO_TOPICS]
AssertionError

**Comment by tvoinarovskyi** [comment]
Hmm, I need to check that. Seems like a bug...

**Comment by hongweishang** [comment]
@tvoinarovskyi hi any response?
