### ISSUE TITLE
AttributeError: 'AIOKafkaProducer' object has no attribute '_producer_magic'

### ISSUE THREAD

**Issue by westhomas** [aio-libs/aiokafka#498]
My producer keeps throwing this exception:
```
Traceback (most recent call last):
  File "/src/simulator/simulator/workers/base.py", line 55, in send
    await self.producer.send_and_wait(self.topic, json.dumps(data, cls=DateTimeJSONEncoder).encode())
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 451, in send_and_wait
    topic, value, key, partition, timestamp_ms)
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 434, in send
    key_bytes, value_bytes = self._serialize(topic, key, value)
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 343, in _serialize
    self._producer_magic)
AttributeError: 'AIOKafkaProducer' object has no attribute '_producer_magic'
```

```python
# Code
class Worker:
    async def send(self, data, namespace):
        from ..settings.base import settings
        self.producer = AIOKafkaProducer(loop=asyncio.get_event_loop(), bootstrap_servers=f'{settings.KAFKA_HOST}:{settings.KAFKA_PORT}')

        await self.producer.start()
        try:
            await self.producer.send_and_wait(self.topic, json.dumps(data, cls=DateTimeJSONEncoder).encode())
        finally:
            await self.producer.stop()

# and later
app.loop.create_task(w.send(...))
```

It seems to work sometimes, but then just seemingly randomly throws this exception.

```
# requirements.pip
aiokafka==0.5.1


# docker-compose.yml
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

**Comment by tvoinarovskyi** [comment]
Don't see any way to get this besides not calling start() method. Probably a check that all methods should not work if start() is not call would help.
Do you call this method concurrently? Why would you create a new consumer every time?

**Comment by tvoinarovskyi** [comment]
I suspect you just need to either create the Producer once, as it's intended to be used. Or don't save the instance under self.producer

**Comment by westhomas** [comment]
I made the producer a local var and it seems to be working fine. I'll circle back and figure out the race condition later. Thanks for the tip!
