### ISSUE TITLE
Cannot Connect to Confluent Cloud using SASL

### ISSUE THREAD

**Issue by sariabod** [aio-libs/aiokafka#627]
**Describe the bug**
Running simple example app against a local Confluent Cluster works fine. Using the exact same code against a Confluent Cloud deployment while enabling SASL causes errors and the connection to be dropped.

**Expected behaviour**
The code should work against a cloud instance of confluent kafka

**Environment (please complete the following information):**
 - aiokafka version (`python -c "import aiokafka; print(aiokafka.__version__)"`): 0.6.0
 - kafka-python version (`python -c "import kafka; print(kafka.__version__)"`): 2.0.1
 - Kafka Broker version (`kafka-topics.sh --version`):  Tried 2.5, 2.4.1, 0.11
 - Other information (Confluent Cloud version, etc.): Confluent Cloud 5.5

**Reproducible example**
```python
from aiokafka import AIOKafkaConsumer
import asyncio

loop = asyncio.get_event_loop()

async def consume():
    consumer = AIOKafkaConsumer(
        'sample_topic',
        loop=loop,
        bootstrap_servers='xxxx.centralus.azure.confluent.cloud:9092',
        sasl_mechanism='PLAIN',
        sasl_plain_password="xxx",
        sasl_plain_username="xxx",
        api_version='2.5'
        )
    # Get cluster layout and join group `my-group`
    await consumer.start()
    try:
        # Consume messages
        async for msg in consumer:
            print("consumed: ", msg.topic, msg.partition, msg.offset,
                  msg.key, msg.value, msg.timestamp)
    finally:
        # Will leave consumer group; perform autocommit if enabled.
        await consumer.stop()

loop.run_until_complete(consume())
```
This is with api_version specified and you get:
```pytb
Traceback (most recent call last):
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 351, in _on_read_task_error
    read_task.result()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 490, in _read
    resp = await reader.readexactly(size)
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 3 bytes read on a total of 352518912 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    loop.run_until_complete(consume())
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 17, in consume
    await consumer.start()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/consumer/consumer.py", line 336, in start
    await self._client.bootstrap()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/client.py", line 205, in bootstrap
    version_hint=version_hint)
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 94, in create_conn
    await conn.connect()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 217, in connect
    await self._do_version_lookup()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 226, in _do_version_lookup
    response = await self.send(version_req)
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
kafka.errors.KafkaConnectionError: KafkaConnectionError: Connection at xxx.centralus.azure.confluent.cloud:9092 closed
Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7fa423f0be10>
```
If you remove the api version and leave as 'auto' default you get:
```pytb
Unable to request metadata from "xxx.centralus.azure.confluent.cloud:9092": KafkaConnectionError: Connection at xxx.centralus.azure.confluent.cloud:9092 closed
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    loop.run_until_complete(consume())
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "test.py", line 17, in consume
    await consumer.start()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/consumer/consumer.py", line 336, in start
    await self._client.bootstrap()
  File "/home/sariabod/source/aio/venv/lib/python3.7/site-packages/aiokafka/client.py", line 233, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.KafkaConnectionError: KafkaConnectionError: Unable to bootstrap from [('xxx.centralus.azure.confluent.cloud', 9092, <AddressFamily.AF_UNSPEC: 0>)]
Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7f026ad9c750>
```

**Comment by sariabod** [comment]
so it looks like ssl is mandatory, must have missed this someplace in the docs. End result is to create a default ssl_context from helper then specify the security_protocol and pass it and the  ssl_context in.

```py
from aiokafka.helpers import create_ssl_context
ssl_context = create_ssl_context()
loop = asyncio.get_event_loop()

async def consume():
    consumer = AIOKafkaConsumer(
        'raw_test',
        loop=loop,
        bootstrap_servers='xxx.centralus.azure.confluent.cloud:9092',
        sasl_mechanism='PLAIN',
        security_protocol='SASL_SSL',
        sasl_plain_password="xxx",
        sasl_plain_username="xxx",
        ssl_context=ssl_context,
 )
```

**Comment by ekeric13** [comment]
Wow this saved me after an hour of reading through docs and struggling. Would be great if you could highlight this more in the docs...
