### ISSUE TITLE
Heartbeat fails if there are no consumed topics

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#87]
Hi,
I've encountered strange behavior. When I create an `AIOKafkaConsumer` and I do not subscribe any topic it fails during next hearbeat on following error:
```
Traceback (most recent call last):
  File "/home/artimi/.PyCharmCE2016.3/config/scratches/scratch_4.py", line 32, in <module>
    main()
  File "/home/artimi/.PyCharmCE2016.3/config/scratches/scratch_4.py", line 18, in main
    loop.run_until_complete(subscribe_later(consumer))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/artimi/.PyCharmCE2016.3/config/scratches/scratch_4.py", line 28, in subscribe_later
    await consumer.stop()
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/consumer.py", line 272, in stop
    yield from self._coordinator.close()
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 134, in close
    yield from self.heartbeat_task
  File "/usr/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 806, in _heartbeat_task_routine
    yield from self._send_req(self.coordinator_id, request)
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/group_coordinator.py", line 159, in _send_req
    resp = yield from self._client.send(node_id, request)
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/client.py", line 309, in send
    if not (yield from self.ready(node_id)):
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/client.py", line 287, in ready
    conn = yield from self._get_conn(node_id)
  File "/home/artimi/.virtualenvs/messaging/lib/python3.5/site-packages/aiokafka/client.py", line 268, in _get_conn
    assert broker, 'Broker id %s not in current metadata' % node_id
AssertionError: Broker id None not in current metadata
```
You can try it with following piece of code:
```python
import asyncio
import aiokafka
import uuid

HEARTBEAT_INTERVAL = 1.0

def main():
	loop = asyncio.get_event_loop()
	consumer = aiokafka.AIOKafkaConsumer(
		loop = loop,
		bootstrap_servers = 'localhost:9092',
		group_id = uuid.uuid4().hex,
		enable_auto_commit = False,
		auto_offset_reset = 'earliest',
		heartbeat_interval_ms = HEARTBEAT_INTERVAL * 1000,
		metadata_max_age_ms = 30000,
	)
	loop.run_until_complete(subscribe_later(consumer))


async def subscribe_later(consumer: aiokafka.AIOKafkaConsumer):
	await consumer.start()
	await asyncio.sleep(1.1 * HEARTBEAT_INTERVAL)
	await consumer.stop()


if __name__ == '__main__':
	main()
```
This happens even if I subscribe and then unsubscribe from some topic before hearbeat is performed.

I tried this on aiokafka 0.1.2 and 0.1.4 with kafka docker container quantlane/kafka:0.9.

**Comment by Artimi** [comment]
I tried this with `aiokafka==0.2.0` and the problem is gone. Thanks for fix!

**Comment by Drizzt1991** [comment]
np
